// Code generated by "stringer -type=Minor"; DO NOT EDIT.

package wsc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReqID-0]
	_ = x[Action-1]
	_ = x[ActionArgs-2]
	_ = x[Container-3]
	_ = x[ContainerIsRunning-4]
	_ = x[Decode-5]
	_ = x[Exited-6]
	_ = x[Inspect-7]
	_ = x[ID-8]
	_ = x[Name-9]
	_ = x[Image-10]
	_ = x[Delete-11]
}

const _Minor_name = "ReqIDActionActionArgsContainerContainerIsRunningDecodeExitedInspectIDNameImageDelete"

var _Minor_index = [...]uint8{0, 5, 11, 21, 30, 48, 54, 60, 67, 69, 73, 78, 84}

func (i Minor) String() string {
	if i >= Minor(len(_Minor_index)-1) {
		return "Minor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Minor_name[_Minor_index[i]:_Minor_index[i+1]]
}
